import type { Metadata } from "next";
import "../styles/globals.css";
import { ThemeProvider } from "./_providers";
import { cn } from "@/lib/utils";
import { fontSans } from "@/lib/fonts";
import { Toaster } from 'sonner';

import TailwindIndicator from "@/components/ui/tailwind-indicator";

export const metadata: Metadata = {
  title: "Edil ozi",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      {/* remove dark as default */}
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.className,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <div className="relative flex min-h-screen flex-col bg-background">
            {children}
          </div>
          <TailwindIndicator />
          <Toaster duration={2500} richColors visibleToasts={3} position="top-center" />
        </ThemeProvider>
      </body>
    </html>
  );
}
